// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace Data.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20180108154809_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Data.Entity.SysUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("SysUser");
                });

            modelBuilder.Entity("Pomelo.AspNetCore.TimedJob.DynamicTimedJob", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128);

                    b.Property<DateTime>("Begin");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("Interval");

                    b.Property<bool>("IsEnabled");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.ToTable("DynamicTimedJob");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DynamicTimedJob");
                });

            modelBuilder.Entity("Pomelo.AspNetCore.TimedJob.EntityFramework.TimedJob", b =>
                {
                    b.HasBaseType("Pomelo.AspNetCore.TimedJob.DynamicTimedJob");


                    b.ToTable("AspNetTimedJobs");

                    b.HasDiscriminator().HasValue("TimedJob");
                });
#pragma warning restore 612, 618
        }
    }
}
